sudo apt install gnome-tweak-tool
sudo apt install vim
sudo apt install tlp
sudo snap install gnome-system-monitor
sudo apt install gdebi
sudo apt install gparted
sudo apt install chrome-gnome-shell
sudo apt install curl
sudo apt install git
sudo apt install gufw
sudo apt install cmake
